// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHhzweHeQhCv8qxQoTaHg1uqCaeopCV-g',
    appId: '1:120647109754:web:b6fe241f094cd762547fc3',
    messagingSenderId: '120647109754',
    projectId: 'newfrecipeapp',
    authDomain: 'newfrecipeapp.firebaseapp.com',
    storageBucket: 'newfrecipeapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDiPeLwsoGtlH4qOdku0jSljrMan1bUvk',
    appId: '1:120647109754:android:290558b0191911f6547fc3',
    messagingSenderId: '120647109754',
    projectId: 'newfrecipeapp',
    storageBucket: 'newfrecipeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtC60W5eupOj-TqFqntbkE_3_TPe9Up3I',
    appId: '1:120647109754:ios:50400aa64436fd66547fc3',
    messagingSenderId: '120647109754',
    projectId: 'newfrecipeapp',
    storageBucket: 'newfrecipeapp.firebasestorage.app',
    iosBundleId: 'com.example.newfrecipeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtC60W5eupOj-TqFqntbkE_3_TPe9Up3I',
    appId: '1:120647109754:ios:50400aa64436fd66547fc3',
    messagingSenderId: '120647109754',
    projectId: 'newfrecipeapp',
    storageBucket: 'newfrecipeapp.firebasestorage.app',
    iosBundleId: 'com.example.newfrecipeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHhzweHeQhCv8qxQoTaHg1uqCaeopCV-g',
    appId: '1:120647109754:web:8bc548f981301535547fc3',
    messagingSenderId: '120647109754',
    projectId: 'newfrecipeapp',
    authDomain: 'newfrecipeapp.firebaseapp.com',
    storageBucket: 'newfrecipeapp.firebasestorage.app',
  );
}
